[globus]
# Globus client ID and endpoint ID for the source 
client_id = 
SOURCE_ENDPOINT_ID = 

# Destination 1: where the raw data will go nightly 
GENERAL_DEST_ENDPOINT_ID = 
GENERAL_DEST_PATH =

# Destination 2: the destination speciifc raw data 
PROJECT_DEST_ENDPOINT_ID = 
PROJECT_DEST_PATH =

# Destination 3: Fortress path for the specific tarred data 
TAPE_ENDPOINT_ID = 
TAPE_BASE_PATH =

[paths]
# Comma separated list of local roots to scan
SOURCE_ROOTS = 

# The Globus path that corresponds to the local roots above
GLOBUS_SOURCE_ROOT = /code/globus_transfer/sandbox/

# Local temp dir on the source 
LOCAL_TAR_STAGING = /Users/rwilfong/Downloads/code/globus_transfer/sandbox/globus_staging/
# The Globus path to that temp folder
GLOBUS_TAR_STAGING = /code/globus_transfer/sandbox/globus_staging/

[keyring]
# Service name for the Keyring set up
service_name = globus_confidential_client

[settings]
# Case-insensitive string to match in the file path to trigger Steps 2 & 3
PROJECT_KEYWORD = widhalm