[paths]
# The local Windows path to start scanning from
SOURCE_ROOTS = D:\Data

# How Globus sees that exact same source folder
GLOBUS_SOURCE_ROOT = /D/Data/

# Where to temporarily save the .tar files before sending to tape
LOCAL_TAR_STAGING = 
# How Globus sees that staging folder
GLOBUS_TAR_STAGING = 

[globus]
client_id = YOUR_CLIENT_ID_HERE

# The UUIDs for your Globus Endpoints
SOURCE_ENDPOINT_ID = 
GENERAL_DEST_ENDPOINT_ID = 
PROJECT_DEST_ENDPOINT_ID =
TAPE_ENDPOINT_ID = 

# The destination root paths (must end in a slash)
GENERAL_DEST_PATH = 
PROJECT_DEST_PATH = 
TAPE_BASE_PATH = 

[settings]
# The script will look for this word in the folder path to sort project files
PROJECT_KEYWORD = widhalm